# Generated by Django 2.0.5 on 2018-06-02 22:04

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaFeature',
            fields=[
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='Polygon Field')),
                ('identifier', models.CharField(default='', max_length=40, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=40)),
                ('description', models.TextField(blank='', default='', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExtraField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='', max_length=20, verbose_name='Key, Value identifier')),
                ('value', models.CharField(default='', max_length=500)),
            ],
            options={
                'ordering': ('key',),
            },
        ),
        migrations.CreateModel(
            name='GeometryCollection',
            fields=[
                ('identifier', models.CharField(default='', max_length=40, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=10, verbose_name='Zone name')),
                ('description', models.CharField(default='', max_length=300, verbose_name='Zone description')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PlatformActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(default='', max_length=10)),
                ('explained_action', models.TextField(default='')),
                ('has_error', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default='anonymous-user', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
        migrations.CreateModel(
            name='PointFeature',
            fields=[
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Point Field')),
                ('identifier', models.CharField(default='', max_length=40, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=40)),
                ('description', models.TextField(blank='', default='', null=True)),
                ('geometry_collection', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.GeometryCollection')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('identifier', models.CharField(default='', max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('top_altitude', models.FloatField(default=0.0)),
                ('max_operator_distance', models.FloatField(default=10.0)),
                ('max_uav_weight', models.FloatField(default=0.0)),
                ('start_at', models.DateField(auto_now=True)),
                ('expiration_time', models.DateField(blank=True, null=True)),
                ('don_t_expire', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='pointfeature',
            name='policy',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.Policy'),
        ),
        migrations.AddField(
            model_name='extrafield',
            name='geometry_collection',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.GeometryCollection'),
        ),
        migrations.AddField(
            model_name='extrafield',
            name='policy',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.Policy'),
        ),
        migrations.AddField(
            model_name='areafeature',
            name='geometry_collection',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.GeometryCollection'),
        ),
        migrations.AddField(
            model_name='areafeature',
            name='policy',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.Policy'),
        ),
    ]
