# Generated by Django 2.0.5 on 2018-06-03 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180603_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geometrycollection',
            name='identifier',
            field=models.CharField(default='', max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='geometrycollection',
            name='name',
            field=models.CharField(default='', max_length=40, verbose_name='Zone name'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='identifier',
            field=models.CharField(default='', max_length=32, primary_key=True, serialize=False),
        ),
    ]
