"""
Django settings for uav_data project.

Generated by 'django-admin startproject' using Django 2.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ofc3jb-vsm6ho7hj*$=qp1!i(5lr6lkurne2l&6$afv3l!ymw7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# APP CONFIGS

# DB CONFIGS
DATABASE_HOST = os.environ.get('DATABASE_HOST', 'localhost')
DATABASE_NAME = os.environ.get('DATABASE_NAME', 'b4ufly')
DATABASE_USER = os.environ.get('DATABASE_USER', 'postgres')
DATABASE_PASS = os.environ.get('DATABASE_PASS', '123456')
DATABASE_PORT = os.environ.get('DATABASE_PORT', '5432')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'rest_framework_swagger',
    'rest_framework',
    'rest_framework_gis',
    'social_django',
    'api',
]


# SOCIAL AUTH LIB SETTINGS
SOCIAL_AUTH_TRAILING_SLASH = False
SOCIAL_AUTH_AUTH0_DOMAIN = 'mdps.auth0.com'
SOCIAL_AUTH_AUTH0_KEY = '3I1g9oEfHJs3RXH52IYf55qnEpBSQljO'
SOCIAL_AUTH_AUTH0_SECRET = 'JzG0sjFZZOWuuCk7Xuwj_IjBym121vOVkkG0TFGweriERYGdRxx6y2sexlMwvTFj'
SOCIAL_AUTH_AUTH0_SCOPE = [
    'openid',
    'profile'
]
AUTHENTICATION_BACKENDS = {
    'api.custom_auth_backend.Auth0',
    'django.contrib.auth.backends.ModelBackend'
}
LOGOUT_URL = "/api/v1/logout"
LOGIN_URL = "/api/v1/login/auth0"
LOGIN_REDIRECT_URL = "/api/v1/dashboard"
LOGOUT_REDIRECT_URL = "/api/v1/collection/"


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'uav_data.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'uav_data.wsgi.application'

DATABASES_AVAILABLE = {
    'production': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': DATABASE_NAME,
        'USER': DATABASE_USER,
        'PASSWORD': DATABASE_PASS,
        'HOST': DATABASE_HOST,
        'PORT': DATABASE_PORT,
    },
    # development-db
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': DATABASE_NAME,
        'USER': DATABASE_USER,
        'PASSWORD': DATABASE_PASS,
        'HOST': DATABASE_HOST,
        'PORT': DATABASE_PORT,
    }
}

DEFAULT_DB = 'default'
selected_database = os.environ.get('SELECTED_DB', DEFAULT_DB)
if selected_database not in DATABASES_AVAILABLE.keys():
    selected_database = DEFAULT_DB

SOUTH_TESTS_MIGRATE = False
DATABASES = {'default': DATABASES_AVAILABLE[selected_database]}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
